// export const FETCH_POSSIBLE_DESTINATIONS = {
//   REQUEST: "FETCH_POSSIBLE_DESTINATIONS_REQUEST",
//   SUCCESS: "FETCH_POSSIBLE_DESTINATIONS_SUCCESS",
//   FAILED: "FETCH_POSSIBLE_DESTINATIONS_FAILED"
// };
