export const FETCH_POSSIBLE_DESTINATIONS = {
  LOADING: 'FETCH_POSSIBLE_DESTINATIONS_LOADING',
  REQUEST: 'FETCH_POSSIBLE_DESTINATIONS_REQUEST',
  SUCCESS: 'FETCH_POSSIBLE_DESTINATIONS_SUCCESS',
  FAILED: 'FETCH_POSSIBLE_DESTINATIONS_FAILED'
};
