export const FETCH_FLIGHT_TICKETS = {
  LOADING: 'FETCH_FLIGHT_TICKETS_LOADING',
  REQUEST: 'FETCH_FLIGHT_TICKETS_REQUEST',
  SUCCESS: 'FETCH_FLIGHT_TICKETS_SUCCESS',
  FAILED: 'FETCH_FLIGHT_TICKETS_FAILED'
};
